[Spark][Improvement]ArcticSparkSessionCatalog need fail back to hive when AMS is not available
NetEase/arctic pull request #1198
Opened 2023-03-07 03:07 UTC by hellojinsilei

## Why are the changes needed?

resolve #1185 

## Brief change log

## How was this patch tested?
- [ ] Add some test cases that check the changes thoroughly including negative and positive cases if possible

- [ ] Add screenshots for manual tests if appropriate

- [x] Run test locally before making a pull request

## Documentation

  - Does this pull request introduces a new feature? (yes / no)
  - If yes, how is the feature documented? (not applicable / docs / JavaDocs / not documented)

2023-03-10 02:46 UTC, baiyangtx requested changes
1. I think remove the `spark.sql.arctic.delegate.enabled` could be removed.
2. all actions use session catalog to load table metadata. and only using arcticCatalog if we have been checked the table format type and have been made sure this is an ArcticTable

2023-03-10 02:46 UTC, baiyangtx commented on spark/v3.1/spark/src/main/java/com/netease/arctic/spark/ArcticSparkSessionCatalog.java
> +import static com.netease.arctic.spark.SparkSQLProperties.DELEGATE_DEFAULT_CATALOG_TABLE_DEFAULT;
I think the `delegate default catalog enabled` could be removed

2023-03-10 02:46 UTC, baiyangtx commented on spark/v3.1/spark/src/main/java/com/netease/arctic/spark/ArcticSparkSessionCatalog.java
>      }
code should like this

```
Table table = getSessionCatalog().loadTable(ident);
if( isArcticTable(table) ) {
   return arcticCatalog.loadTable( ident)
}
return table;
```

2023-03-10 02:46 UTC, baiyangtx commented on spark/v3.1/spark/src/main/java/com/netease/arctic/spark/ArcticSparkSessionCatalog.java
>      // no need to check table existence to determine which catalog to use. if a table doesn't exist then both are
```
Table table = loadTable(ident);
if( isArcticTable ) {
   arcticCatalog.alterTable(ident)
} else {
   sessionCatalog.alterTable( ident )
}
```

2023-03-10 02:46 UTC, baiyangtx commented on spark/v3.1/spark/src/main/java/com/netease/arctic/spark/ArcticSparkSessionCatalog.java
>        getSessionCatalog().renameTable(from, to);
same like alter

2023-03-10 05:45 UTC, zhoujinsong commented
@hellojinsilei Could you please complete the PR's description as the Arctic Community Guidld：
https://docs.google.com/document/d/1Pwv1LflW3z5yq34qDpEYwSxOB3LIE5qoKQ_5Sv0IV1Y/edit?usp=sharing

2023-03-14 08:14 UTC, baiyangtx approved these changes

2023-03-14 08:40 UTC, merged