[ARCTIC-1214][ams] add createOptimizeGroup http service
NetEase/arctic pull request #1215
Opened 2023-03-10 06:42 UTC by ShawHee

## Why are the changes needed?
During the running of Arctic, if a new record is inserted into the optimize_group table, it will not be updated to optimizeQueues. Instead, you need to restart AMS to make the new optimize group work.

So I add an http interface createOptimizeGroup and a method createQueue(), enables  add optimize group while AMS is runing.

## Brief change log
  - *Add the 'createQueue' method to the OptimizeQueueService in the ams-server modules*
  - *Add the 'createOptimizeGroup' method to the OptimizerController in the ams-server modules*
  - *Add a post url to AmsRestServer.startRestServer  in the ams-server modules*

## How was this patch tested?

- [ ] Run test locally before making a pull request

## Documentation

 *how to use*
 - url:   /ams/v1/optimize/optimizerGroups/
 - method:  post
 - param:  like
 ```
{
    "name":"test_group",
    "container":"container1",
    "schedulePolicy": "quota",
    "properties":{"taskmanager.memory":2048,"jobmanager.memory":2048}
}
```

2023-03-10 08:19 UTC, Aireed reviewed
I left some comment, PTAL

2023-03-10 09:29 UTC, ShawHee commented on ams/ams-server/src/main/java/com/netease/arctic/ams/server/controller/OptimizerController.java
> +      ctx.json(new ErrorResponse(HttpCode.BAD_REQUEST, "Failed to create optimize group", ""));
Added e.getMessage() to response

2023-03-10 09:30 UTC, ShawHee commented on ams/ams-server/src/main/java/com/netease/arctic/ams/server/service/impl/OptimizeQueueService.java
> +        throw new MetaException("optimize group name:" + name + " already exists");
done

2023-03-10 09:31 UTC, ShawHee commented on ams/ams-server/src/test/java/com/netease/arctic/ams/server/controller/OptimizerControllerTest.java
> +      assert result.getCode() == 200;
Added 3 abnormal cases
-  abnormal case 1, optimize group name already exists, code =400
-  abnormal case 2, can not find such container config, code =400
-  abnormal case 3, scheduling policy only can be quota and balanced, code =400

2023-03-10 09:32 UTC, ShawHee commented on ams/ams-server/src/main/java/com/netease/arctic/ams/server/service/impl/OptimizeQueueService.java
> +          "can not find such container config named" + container);
done

2023-03-11 10:20 UTC, shidayang requested changes

2023-03-11 10:20 UTC, shidayang commented on ams/ams-server/src/main/java/com/netease/arctic/ams/server/service/impl/OptimizeQueueService.java
> +    }
It would be better to add a method like "getContainers(String contanier)"

2023-03-13 07:02 UTC, shidayang commented
@ShawHee Some unit test failed

2023-03-13 08:18 UTC, ShawHee commented
> 

I fixed a checkstyle problem, now it works.

2023-03-13 11:09 UTC, Aireed approved these changes
LGTM

2023-03-13 11:58 UTC, shidayang approved these changes

2023-03-13 12:00 UTC, merged

2023-03-13 12:01 UTC, shidayang commented
Thanks for working on this