FlinkOptimizer automatically retries after failover
NetEase/arctic pull request #1248
Opened 2023-03-17 07:45 UTC by Sixkd

# Background
https://github.com/NetEase/arctic/issues/725
When a optimize task is executed by optimizer, changes (such as failover, attempt or manual restart) occur, and the optimizing process is interrupted. The ams does not know about the interrupts. The ams changes the optimize status to failed and tries again after the merger task times out,delaying the optimize task 

# Goals
For Flink-external optimzer ,ams cans know that the optimizer has experienced a state change (such as failover, attempt or manual restart), and promptly sets the previous optimize process to fail and retries, reducing latency

# Non-goals
Optimizer other than Flinks-external-Optimzer

# Overall Design
The Reporter class of flink-optimizer  and AMS heartbeat processing

# Implementation Plan
Flink-external-optimizer
1、Flink-optimizer args adds flink api's url prefix
2、Get the last_modification via flink's rest api and report the last_modification to ams via heartbeat as a status identification

# AMS-OptimizerService.checkOptimizerRetry
1、If the newReportData status identification exists and the new and old status identification is inconsistent, the status of the optimzer has changed
2、Obtain the optimizer-id and query the task with create_time smaller than last_modification being executed by the optimzer. Set the task to failed
3、Update OptimizerState

# Test Plan
Restart flink-optimzer. Observe that the task corresponding to optimize_task is set to failed because the optimizer job has occurred retry.

# Compatibility, Deprecation, and Migration Plan
This parameter is valid only for flink tasks with a rest-prefix and a specified id in the args

2023-03-17 08:39 UTC, closed without merging

2023-03-29 05:03 UTC, wangtaohz requested changes
@Sixkd Thanks for your contribution. I have left some comments, please take a look.

2023-03-29 05:03 UTC, wangtaohz commented on ams/ams-server/src/main/java/com/netease/arctic/ams/server/service/impl/OptimizerService.java
> +          if (baseOptimizeTask.getCreateTime()  < Long.parseLong(statusIdentification)) {
Checking `create time of task` < `last modify time of optimizer` is not safe, I recommend checking `execute time of task` < `last modify time of optimizer`.

We can get the execute time of task by 
```
OptimizeTaskItem optimizeTask = XXX;
optimizeTask.getOptimizeRuntime().getExecuteTime();
```

2023-03-29 05:38 UTC, wangtaohz commented
I am wondering if there is a simpler and more general way to get the `last-modification` time of the flink job instead of the REST API of yarn.

For example, we can keep the time when `FlinkReporter` is created, like 
```
  private long createTime;

  public FlinkReporter(BaseTaskReporter taskReporter, BaseToucher toucher, OptimizerConfig optimizerConfig) {
    this.taskReporter = taskReporter;
    this.toucher = toucher;
    this.heartBeatInterval = optimizerConfig.getHeartBeat();
    this.createTime = System.currentTimeMillis();
  }

```

then we can use the `createTime` of `FlinkReporter` as the `last-modification`, since there is only one `FlinkReporter` instance for a flink job.

Do you think it's practicable? @Sixkd

2023-03-29 05:51 UTC, hameizi commented on ams/ams-server/src/main/java/com/netease/arctic/ams/server/service/impl/OptimizerService.java
> +        optimizerMapper.updateOptimizerState(reportData.optimizerId, optimizerinstance,
Yes, for external optimizer we don't store optimizerinstance

2023-04-06 03:34 UTC, wangtaohz reviewed
I left some comment, please take a look @Sixkd

2023-04-06 03:34 UTC, wangtaohz commented on optimizer/src/main/java/com/netease/arctic/optimizer/flink/FlinkReporter.java
> +
`JOB_OVERVIEW_REST_API` `HIGH_AVAILABILITY_CLUSTER_ID` `LAST_MODIFICATION` are useless, we should remove them.

2023-04-06 03:34 UTC, wangtaohz commented on optimizer/src/main/java/com/netease/arctic/optimizer/flink/FlinkReporter.java
> +  private long createTime;
The field `createTime` may be `final`.
It's better to refactor the constructors to 
```
  public FlinkReporter(BaseTaskReporter taskReporter, BaseToucher toucher, OptimizerConfig optimizerConfig) {
    this.taskReporter = taskReporter;
    this.toucher = toucher;
    this.heartBeatInterval = optimizerConfig.getHeartBeat();
    this.createTime = System.currentTimeMillis();
  }

  public FlinkReporter(OptimizerConfig config) {
    this(new BaseTaskReporter(config), new BaseToucher(config), config);
  }
```

2023-04-06 12:36 UTC, wangtaohz approved these changes
LGTM.