[AMS] Move aws sdk dependency profile
NetEase/arctic pull request #1530
Opened 2023-06-07 10:01 UTC by XBaith

## Why are the changes needed?

Fix #1479

## Brief change log

## How was this patch tested?
- [ ] Add some test cases that check the changes thoroughly including negative and positive cases if possible

- [ ] Add screenshots for manual tests if appropriate

- [x] Run test locally before making a pull request

## Documentation

  - Does this pull request introduces a new feature? (no)
  - If yes, how is the feature documented? (not documented)

2023-06-07 10:50 UTC, baiyangtx approved these changes
LGTM

2023-06-07 10:55 UTC, baiyangtx requested changes
The dependencies shoud be added to core/pom.xml and manager the version in /pom.xml via dependencyManagement.

2023-06-07 10:55 UTC, baiyangtx commented on pom.xml
> +            <dependencies>
This should be dependencyManagement.

2023-06-07 10:55 UTC, shidayang requested changes

2023-06-07 10:55 UTC, shidayang commented on pom.xml
> +            <dependencies>
This will cause all module has these dependencies

2023-06-09 01:46 UTC, shidayang requested changes

2023-06-09 01:46 UTC, shidayang commented on core/pom.xml
> +        <dependency>
Remove this dependency

2023-06-09 02:28 UTC, XBaith commented on core/pom.xml
> +        <dependency>
Don

2023-06-09 11:31 UTC, baiyangtx approved these changes

2023-06-09 11:32 UTC, merged