[ARCTIC-1650][AMS]: Optimize the serialization of table_optimizing_process.rewrite_input using gzip
NetEase/arctic pull request #1665
Opened 2023-07-07 02:18 UTC by shidayang

## Why are the changes needed?
fix #1650 and reduce the bytes when save record to table `table_optimizing_process `

## Brief change log
Add gzip in Object2ByteArrayConvert

## How was this patch tested?
- [ ] Add some test cases that check the changes thoroughly including negative and positive cases if possible

- [ ] Add screenshots for manual tests if appropriate

- [ ] Run test locally before making a pull request

## Documentation

  - Does this pull request introduces a new feature? (yes / **no**)
  - If yes, how is the feature documented? (not applicable / docs / JavaDocs / **not documented**)

2023-07-07 02:33 UTC, baiyangtx requested changes
You need add licences to the new added files.

2023-07-07 02:33 UTC, baiyangtx commented on ams/server/src/main/java/com/netease/arctic/server/utils/CompressUtil.java
> +package com.netease.arctic.server.utils;
Lack licences

2023-07-07 02:33 UTC, baiyangtx commented on ams/server/src/main/java/com/netease/arctic/server/persistence/converter/Object2ByteArrayConvert.java
> +    ps.setBytes(i, CompressUtil.gzip(SerializationUtil.simpleSerialize(parameter).array()));
Have you considered using Kryo? The size of Kryo is smaller then Java default serializer

2023-07-10 01:41 UTC, zhoujinsong commented on ams/server/src/main/java/com/netease/arctic/server/utils/CompressUtil.java
> +  public static byte[] gzip(byte[] bytes) {
add javadoc for util method.

2023-07-10 01:41 UTC, zhoujinsong commented on ams/server/src/test/java/com/netease/arctic/server/util/CompressUtilTest.java
> +public class CompressUtilTest {
lack of licence.

2023-07-10 05:42 UTC, zhoujinsong approved these changes
LGTM.

2023-07-10 05:52 UTC, baiyangtx approved these changes
LGTM

2023-07-10 05:55 UTC, merged