[Spark]Spark3 hive catalog junit
NetEase/arctic pull request #213
Opened 2022-08-23 08:36 UTC by HuangFru

fix create table in hive module
add getOrDefault in map in OverwriteBaseFiles
add mergeOnRead tests

2022-08-23 08:44 UTC, baiyangtx requested changes

2022-08-23 08:44 UTC, baiyangtx commented on spark/v3.1/spark/src/test/java/com/netease/arctic/spark/SparkTestContext.java
> +  }
adapt hive write should in hive test context.   
all common method about hive should be in test context

2022-08-23 08:44 UTC, baiyangtx commented on spark/v3.1/spark/src/test/java/com/netease/arctic/spark/TestKeyedMergeOnRead.java
> +public class TestKeyedMergeOnRead extends SparkTestContext {
TestKeyedHiveTableMergeOnRead

2022-08-23 08:44 UTC, baiyangtx commented on spark/v3.1/spark/src/test/java/com/netease/arctic/spark/TestKeyedMergeOnRead.java
> +    assertContainIdSet(rows, 0, 1,2,3,4,5,6,7,8,9,10);
why contain id=0 ?

2022-08-23 08:44 UTC, baiyangtx commented on spark/v3.1/spark/src/test/java/com/netease/arctic/spark/TestKeyedMergeOnRead.java
> +    sql("SET noUserSpecifiedNumPartition=false");
is this command necessary？

2022-08-23 08:44 UTC, baiyangtx commented on spark/v3.1/spark/src/test/java/com/netease/arctic/spark/TestKeyedMergeOnRead.java
> +    assertContainIdSet(rows, 0, 7, 8, 9, 10);
why contain id=0?

2022-08-23 08:44 UTC, baiyangtx commented on spark/v3.1/spark/src/test/java/com/netease/arctic/spark/TestKeyedMergeOnRead.java
> +
mor could add some position-delete tests

2022-08-23 08:46 UTC, HuangFru commented on spark/v3.1/spark/src/test/java/com/netease/arctic/spark/TestKeyedMergeOnRead.java
> +    assertContainIdSet(rows, 0, 7, 8, 9, 10);
that parameter is idIndex

2022-08-23 08:56 UTC, HuangFru commented on spark/v3.1/spark/src/test/java/com/netease/arctic/spark/TestKeyedMergeOnRead.java
> +    sql("SET noUserSpecifiedNumPartition=false");
not necessary, i will delete it

2022-08-24 08:25 UTC, baiyangtx approved these changes

2022-08-24 08:39 UTC, merged