[SPARK]update spark doc
NetEase/arctic pull request #392
Opened 2022-09-21 06:17 UTC by hellojinsilei

## Why are the changes needed?

Arctic Spark 0.3.2 support Insert/update/delete to primary key table，so update spark doc.

## Documentation
https://arctic.netease.com/ch/spark/spark-dml/#select-from-change-table

2022-09-21 06:27 UTC, baiyangtx requested changes

2022-09-21 06:27 UTC, baiyangtx commented on site/docs/ch/spark/spark-ddl.md
> +`CREATE TABLE ... LIKE` 语法会将表结构包括主键、分区以及表配置复制到新表中，但不会复制数据。
标注一下，因为 primary key 不是 spark 标准语法，所以如果源表是 arctic 表，且有主键，新建表可以复制主键这部分的schema信息，如果是其他类型的表，则无法复制

2022-09-21 07:22 UTC, baiyangtx requested changes

2022-09-21 07:22 UTC, baiyangtx commented on site/docs/ch/spark/spark-get-started.md
> +> 在当前版本中, 在有主键表和无主键表上都支持 insert into 语法
insert or upsert 的参数需要说明一下。

2022-09-22 03:00 UTC, zhoujinsong commented on site/docs/ch/spark/spark-get-started.md
> +> 在当前版本中, 在有主键表和无主键表上都支持 insert into 语法
Maybe you should remove this note if all kind of table are  supported now.

2022-09-22 03:00 UTC, zhoujinsong commented on site/docs/ch/spark/spark-ddl.md
> +???+note "因为 primary key 不是 spark 标准语法，所以如果源表是 arctic 表，且有主键，新建表可以复制主键这部分的schema信息，如果是其他类型的表，则无法复制"
`Spark` and `Arctic` are proper nouns so we set the first character to upper case.
A white space should arround the English word in Chinese document.

2022-09-22 03:04 UTC, zhoujinsong commented
@hellojinsilei Could you please rename this PR's name to describe what you do in more detail ？

2022-09-22 05:44 UTC, zhoujinsong approved these changes
LGTM.

2022-09-22 08:07 UTC, baiyangtx approved these changes

2022-09-22 08:08 UTC, merged