[ARCTIC-462][AMS] Add implement for RewriteFiles to support Hive
NetEase/arctic pull request #463
Opened 2022-10-12 02:31 UTC by hzluting

## Why are the changes needed?
fix #462 Add implement for RewriteFiles to support Hive

## Brief change log

  - *Add implement for RewriteFiles to support Hive*

## How was this patch tested?
- [ ] Add some test cases that check the changes thoroughly including negative and positive cases if possible

- [ ] Add screenshots for manual tests if appropriate

- [ ] Run test locally before making a pull request

## Documentation

  - Does this pull request introduces a new feature? (yes / no)
  - If yes, how is the feature documented? (not applicable / docs / JavaDocs / not documented)

2022-10-12 03:23 UTC, baiyangtx approved these changes

2022-10-13 02:11 UTC, zhoujinsong requested changes
@hzluting I left some comments. PTAL

2022-10-13 02:11 UTC, zhoujinsong commented on hive/src/test/java/com/netease/arctic/hive/op/TestRewriteFiles.java
> +  public void testOverwriteUnkeyedPartitionTable() throws TException {
```suggestion
  public void testRewriteUnkeyedPartitionTable() throws TException {
```

2022-10-13 02:11 UTC, zhoujinsong commented on hive/src/test/java/com/netease/arctic/hive/op/TestRewriteFiles.java
> +    // ================== test overwrite all partition
```suggestion
    // ================== test rewrite all partition
```

2022-10-13 02:11 UTC, zhoujinsong commented on hive/src/test/java/com/netease/arctic/hive/op/TestRewriteFiles.java
> +    // ================== test overwrite all partition
```suggestion
    // ================== test rewrite all partition
```

2022-10-13 02:11 UTC, zhoujinsong commented on hive/src/test/java/com/netease/arctic/hive/op/TestRewriteFiles.java
> +    // ================== test overwrite table
```suggestion
    // ================== test rewrite table
```

2022-10-13 02:57 UTC, zhoujinsong approved these changes
LGTM.

2022-10-13 03:18 UTC, hzluting commented
> @hzluting I left some comments. PTAL

2022-10-13 03:49 UTC, merged