[ARCTIC-462][AMS]Fix only rewrite DeleteFiles problem for support Hive
NetEase/arctic pull request #468
Opened 2022-10-13 12:42 UTC by hzluting

## Why are the changes needed?
fix #462 
Full optimize will use RewriteFiles to delete DeleteFiles, but RewriteHiveFiles will overwrite DataFiles commit info before, will cause hive partition info incorrect.

## Brief change log

  - *when there  have no addDataFiles or deleteDataFiles, don't need to support hive*

## How was this patch tested?
- [ ] Add some test cases that check the changes thoroughly including negative and positive cases if possible

- [ ] Add screenshots for manual tests if appropriate

- [ ] Run test locally before making a pull request

## Documentation

  - Does this pull request introduces a new feature? (yes / no)
  - If yes, how is the feature documented? (not applicable / docs / JavaDocs / not documented)

2022-10-14 01:43 UTC, zhoujinsong requested changes
@hzluting  I left some comments. PTAL

2022-10-14 01:43 UTC, zhoujinsong commented on hive/src/main/java/com/netease/arctic/hive/op/UpdateHiveFiles.java
> +    // if no DataFiles to add or delete in Hive location, only commit to iceberg
I recommend add this if statement  before line 116 to avoid duplicate code at line 101-105 and line 110-114

2022-10-14 02:06 UTC, hzluting commented on hive/src/main/java/com/netease/arctic/hive/op/RewriteHiveFiles.java
> +    if (CollectionUtils.isEmpty(addFiles) && CollectionUtils.isEmpty(deleteFiles)) {
yes，I will remove it

2022-10-14 03:39 UTC, zhoujinsong commented on hive/src/main/java/com/netease/arctic/hive/op/OverwriteHiveFiles.java
> +        "Unpartition support hive table don't support overwriteByRowFilter");
```suggestion
        "Unpartitioned hive table support alwaysTrue expression only");
```

2022-10-14 03:39 UTC, zhoujinsong commented on hive/src/main/java/com/netease/arctic/hive/op/UpdateHiveFiles.java
> +    boolean isNoHiveDataFiles = CollectionUtils.isEmpty(addFiles) && CollectionUtils.isEmpty(deleteFiles) &&
I recommend to change `isNoHiveDataFiles` to `noHiveDataFilesChanged`

2022-10-17 01:45 UTC, zhoujinsong approved these changes
LGTM.

2022-10-17 01:45 UTC, merged